### PR TITLE
Create docker container with node v5.3.0.

### LINKED ISSUE #1: Create a docker container with the lastest stable version of node.
The latest version is v5.3.0. https://nodejs.org/en/download/stable/. This will be used to help solve https://github.com/lynxtp/synchrony-exception-management/issues/3.

### PR DESCRIPTION
**Pull request by tvaughan**
Fixes #1

### CODE REVIEW

**Comment by stevebrewer** [comment]
Make sure I'm following:
- Creates a new docker image based on our ubuntu image (which includes curl).
- The docker image downloads node (puts it in a temp directory, creates the install directory, un-tar/gz's the tarball, deletes the temp dir")
- Instructions on how to run it in the readme

I'm not following the node file - is that doing what the readme says to do?

**Comment by tvaughan** [comment]
> Creates a new docker image based on our ubuntu image (which includes curl).

Correct.

> The docker image downloads node (puts it in a temp directory, creates the install directory, un-tar/gz's the tarball, deletes the temp dir")

Correct. This is done all in one step because each "step" or "instruction" in a Dockerfile is used by Docker to build a container in "layers". Each new layer is just a diff from the previous layer. If we did each of these steps separately then there would be a "layer" that contains the downloaded tarball. Anyone who wants to run this docker container would then have to download the layer that contains the tarball. By downloading, extracting, and deleting the tarball in the same step we avoid creating a later that contains the tarball. It does make the Dockerfile harder to read but this is the pattern everyone recommends so I went with it.

> I'm not following the node file - is that doing what the readme says to do?

Correct. The `node` script that's included is a little bit more sophisticated than what's in README.md. The `node` script uses the name of the script as the name of the program that's run in the container. So this pull-request includes `npm` which is just a symbolic link to `node`. So `npm` will be run in the container when the `npm` script is run. For example, on my laptop:

```
$ ll node npm 
-rwxr-xr-x 1 tvaughan staff 239 Dec 29 10:57 node*
lrwxr-xr-x 1 tvaughan staff   4 Dec 29 11:35 npm -> node*
$ ./node --version
v5.3.0
$ ./npm --version
3.3.12
```

Does this make sense?

**Comment by stevebrewer** [comment]
Not quite following - if npm is just pointing to node - why would it return a different version?

**Comment by tvaughan** [comment]
> Not quite following - if npm is just pointing to node - why would it return a different version?

Sorry. The magic is line on line 5: https://github.com/lynxtp/docker-node/pull/2/files#diff-36c4536996ca5615dcf9911f068786dcR5 This says that `/opt/node/bin/<name-of-the-shell-script>` will be run in the container. So when the `node` shell script is run, `/opt/node/bin/node` is run in the container. And when the `npm` shell script (really a symbolic link to `node`) is run, `/opt/node/bin/npm` is run in the container.

**Comment by stevebrewer** [comment]
Ahhh, ok, I follow. :+1:

**Comment by rebeccamadsen** [comment]
+1

**Pull request merged**
